#!/usr/bin/env bash
# prescan-wire-claude-md.sh — deterministic CLAUDE.md managed-block injection.
# Inserts or replaces the <!-- ticket-auto:agent-knowledge --> block in a repo's
# CLAUDE.md. Zero LLM involvement — replaces the fragile "LLM writes sed" pattern.
# Idempotent: running twice produces the same result.
set -eo pipefail

# ── Usage ─────────────────────────────────────────────────────────────────────

usage() {
  cat >&2 <<'EOF'
Usage: prescan-wire-claude-md.sh --claude-md <path> --prescan-index <path> [--repo-slug <slug>] [--wiki-root <path>]

Inserts or replaces a managed block in CLAUDE.md pointing to prescan docs.
If the START/END markers exist, content between them is replaced.
If they don't exist, the block is appended at the end of the file.

Also, when --wiki-root is given, ensures a "Cross-repo" row exists in the
prescan INDEX.md's "Lookup by Topic" table pointing at WIKI_ROOT/index.md —
prescan is per-repo and cannot answer a cross-repo question, so its own
routing table should say where to go for one (wiki-cross-repo-knowledge-layer).

Options:
  --claude-md <path>     Path to the repo's CLAUDE.md
  --prescan-index <path> Path to the prescan INDEX.md for this repo
  --repo-slug <slug>     Repo slug (optional, derived from path if omitted)
  --wiki-root <path>     WIKI_ROOT path (optional). When set, ensures a
                         Cross-repo row in --prescan-index's Lookup by Topic
                         table pointing at <wiki-root>/index.md.
  --dry-run              Print what would be done, don't modify files

Exit: 0 on success, 1 if CLAUDE.md not found, 2 on write error
EOF
  exit 2
}

# ── Block content ──────────────────────────────────────────────────────────────

START_MARKER="<!-- ticket-auto:agent-knowledge START -->"
END_MARKER="<!-- ticket-auto:agent-knowledge END -->"

_build_block() {
  local index_path="$1" slug="${2:-}"
  local docs_dir
  docs_dir=$(dirname "$index_path")
  local repos_root
  repos_root=$(dirname "$(dirname "$docs_dir")")

  cat <<BLOCKEOF
$START_MARKER
## Agent Knowledge

Pre-built agent-knowledge docs are at \`.ticket-auto/$slug/docs/\`.
See the [Prescan Index]($index_path) for topic and service lookup tables,
or [Overview]($docs_dir/overview.md) for architecture overview.

These files are machine-generated by \`/ticket-prescan\`. Do not edit manually.
$END_MARKER
BLOCKEOF
}

# ── Cross-repo row in INDEX.md ──────────────────────────────────────────────────
# Ensures a "| Cross-repo | <wiki-root>/index.md |" row exists in the "Lookup by
# Topic" table of the prescan INDEX.md. Idempotent: any prior Cross-repo row
# (e.g. pointing at a stale wiki-root value) is dropped and replaced, never
# duplicated. INDEX.md is normally regenerated wholesale by prescan-docs.sh
# before this script runs, so in practice there is nothing to drop — this
# handles the case of this script being re-run standalone.
_wire_index_cross_repo_row() {
  local index_path="$1" wiki_root="$2" dry_run="$3"

  [ -z "$wiki_root" ] && return 0
  [ -f "$index_path" ] || return 0

  local row="| Cross-repo | ${wiki_root%/}/index.md |"

  if [ "$dry_run" = "true" ]; then
    echo "[dry-run] Would ensure cross-repo row in $index_path: $row"
    return 0
  fi

  local tmp="${index_path}.tmp.$$"
  awk -v row="$row" -v marker="## Lookup by Topic" '
    BEGIN { in_topic = 0; inserted = 0 }
    /^\| Cross-repo \|/ { next }
    {
      print
      if ($0 == marker) { in_topic = 1 }
      else if (in_topic && $0 ~ /^\|-+\|-+\|$/ && !inserted) {
        print row
        inserted = 1
        in_topic = 0
      }
    }
  ' "$index_path" >"$tmp" && mv "$tmp" "$index_path"
}

# ── Main ───────────────────────────────────────────────────────────────────────

main() {
  local claude_md="" index_path="" slug="" dry_run="false" wiki_root=""

  while [[ $# -gt 0 ]]; do
    case "$1" in
    --claude-md)
      claude_md="${2:-}"
      shift 2
      ;;
    --prescan-index)
      index_path="${2:-}"
      shift 2
      ;;
    --repo-slug)
      slug="${2:-}"
      shift 2
      ;;
    --wiki-root)
      wiki_root="${2:-}"
      shift 2
      ;;
    --dry-run)
      dry_run="true"
      shift
      ;;
    --help | -h) usage ;;
    *)
      echo "Unknown flag: $1" >&2
      usage
      ;;
    esac
  done

  [ -z "$claude_md" ] && {
    echo "ERROR: --claude-md is required" >&2
    usage
  }
  [ -z "$index_path" ] && {
    echo "ERROR: --prescan-index is required" >&2
    usage
  }

  if [ ! -f "$claude_md" ]; then
    echo "ERROR: CLAUDE.md not found: $claude_md" >&2
    exit 1
  fi

  if [ -z "$slug" ]; then
    slug=$(basename "$(dirname "$(dirname "$index_path")")")
  fi

  # Cross-repo row in INDEX.md — independent of the CLAUDE.md block below, so it
  # runs first and its own dry-run/no-op paths return internally without
  # affecting the CLAUDE.md wiring that follows.
  _wire_index_cross_repo_row "$index_path" "$wiki_root" "$dry_run"
  if [ -n "$wiki_root" ] && [ -f "$index_path" ] && [ "$dry_run" != "true" ]; then
    echo "PRESCAN_WIRE_INDEX_STATUS=done"
  fi

  local block_text
  block_text=$(_build_block "$index_path" "$slug")
  local tmp="${claude_md}.tmp.$$"

  if grep -qF "$START_MARKER" "$claude_md" 2>/dev/null; then
    # Markers exist — replace content between them
    if [ "$dry_run" = "true" ]; then
      echo "[dry-run] Would replace managed block in $claude_md"
      echo "$block_text"
      return 0
    fi
    # Use awk for multi-line replacement between markers
    awk -v start="$START_MARKER" -v end="$END_MARKER" -v block="$block_text" '
      BEGIN { in_block = 0 }
      $0 == start { print block; in_block = 1; next }
      $0 == end   { in_block = 0; next }
      !in_block   { print }
    ' "$claude_md" >"$tmp" && mv "$tmp" "$claude_md"
  else
    # No markers — append block at end
    if [ "$dry_run" = "true" ]; then
      echo "[dry-run] Would append managed block to $claude_md"
      echo "$block_text"
      return 0
    fi
    cp "$claude_md" "$tmp"
    echo "" >>"$tmp"
    echo "$block_text" >>"$tmp"
    mv "$tmp" "$claude_md"
  fi

  echo "PRESCAN_WIRE_STATUS=done"
  echo "PRESCAN_WIRE_FILE=$claude_md"
}

# ── Dispatch ───────────────────────────────────────────────────────────────────

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  main "$@"
fi
