#!/usr/bin/env bash
# wiki-bootstrap.sh — existence-gate scaffolding for {WIKI_ROOT}.
#
# Deterministic bash primitive for the wiki-bootstrap capability
# (openspec/changes/adr-governance-gate/specs/wiki-bootstrap/spec.md). Creates
# index.md, decisions/index.md, and glossary.md from fixed templates so a
# freshly configured WIKI_ROOT is usable on first run — no model involvement,
# no overwrite of anything already present.
#
# index.md's File Registry / Lookup by Topic / Lookup by Service sections
# match the table shape lib/prescan-route.sh already parses (`| col | col |`
# rows, `(no entries yet)` placeholder skipped by _topic_matches) and the
# shape lib/prescan-docs.sh's own INDEX.md writer produces — one table
# convention, not a second one invented here.
#
# decisions/index.md is generated by sourcing adr-store.sh's own
# _adr_regen_index rather than hand-writing an equivalent template, so the
# empty-store shape can never drift from what adr_write regenerates on the
# first real ADR.
#
# Sourceable lib (wiki_bootstrap) and standalone CLI.
#
# -u (nounset) intentionally omitted: Claude Code shell snapshots inject
# ZSH_VERSION references that trigger false-positive "unbound variable"
# errors in this bash version when nounset is active. Repo convention.
set -eo pipefail

_WB_SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=./adr-store.sh
source "${_WB_SCRIPT_DIR}/adr-store.sh"

WIKI_BOOTSTRAP_SCHEMA_VERSION=1

# ── templates ────────────────────────────────────────────────────────────────

_wb_index_template() {
  cat <<'EOF'
# Wiki Index

Freshness-linted wiki root. Every content file under here carries the
frontmatter schema `lib/wiki-check.sh` lints (see `wiki-maintenance` SKILL.md
Step 2b) — `verified_at`, `verified_against`, `stale_after`, `verified`.

## File Registry

Every wiki file gets a row here. `lib/wiki-verify.sh` checks this table
against the filesystem in both directions.

| File | Description |
|---|---|
| (no entries yet) | |

## Lookup by Topic

Parsed by `lib/prescan-route.sh` for deterministic keyword→file routing.

| Topic | File |
|-------|------|
| (no entries yet) | |

## Lookup by Service

| Service | File |
|---------|------|
| (no entries yet) | |
EOF
}

_wb_glossary_template() {
  local today
  today=$(_adr_now_date)
  cat <<EOF
---
services: []
entities: []
flows: []
keywords: [glossary]
related: []
verified_at: "${today}"
verified_against: {repo: "", sha: ""}
stale_after: 90
verified: machine-verified
---

# Glossary

Settled terminology for this wiki and ADR store. See
docs/glossary-schema.md for the entry schema. Read this before drafting ADR
prose — the gate uses the preferred term, not a new synonym.

(no entries yet)
EOF
}

# ── bootstrap ────────────────────────────────────────────────────────────────

_wb_usage() {
  cat >&2 <<'EOF'
Usage: wiki-bootstrap.sh [--wiki-root <path>]

Scaffolds {WIKI_ROOT}/index.md, {WIKI_ROOT}/decisions/index.md, and
{WIKI_ROOT}/glossary.md from fixed templates. No-op when WIKI_ROOT is unset
(--wiki-root omitted and no WIKI_ROOT env var) — a project with no wiki is
unaffected. No-op per artifact that already exists — only what is missing is
scaffolded.

Output:
  WIKI_BOOTSTRAP_STATUS   ok | skipped
  WIKI_BOOTSTRAP_REASON   no-wiki-root (skipped only)
  WIKI_BOOTSTRAP_CREATED  comma-separated list of artifacts created (may be empty)

Usage: wiki-bootstrap.sh term-drift [--wiki-root <path>]

Scans {WIKI_ROOT}/glossary.md for Avoid: synonyms and reports every wiki
file or ADR using one instead of the preferred term.

Output: TERM_DRIFT|<file>|<avoided-term>|<preferred-term> per occurrence.
Exit: 0 clean, 1 violations found.

Exit: 0 always (bootstrap failure is soft — never blocks a caller)
EOF
}

_wb_die_usage() {
  _wb_usage
  exit 2
}

# wiki_bootstrap [<wiki-root>]
# Sourceable entry point. Falls back to $WIKI_ROOT when no arg is given.
wiki_bootstrap() {
  local wiki_root="${1:-${WIKI_ROOT:-}}"

  if [ -z "$wiki_root" ]; then
    echo "WIKI_BOOTSTRAP_STATUS=skipped"
    echo "WIKI_BOOTSTRAP_REASON=no-wiki-root"
    echo "WIKI_BOOTSTRAP_CREATED="
    return 0
  fi

  mkdir -p "$wiki_root" 2>/dev/null || true

  local created=()

  if [ ! -f "$wiki_root/index.md" ]; then
    _wb_index_template >"$wiki_root/index.md.tmp.$$" && mv "$wiki_root/index.md.tmp.$$" "$wiki_root/index.md"
    created+=("index.md")
  fi

  local decisions_dir
  decisions_dir=$(_adr_decisions_dir "$wiki_root")
  if [ ! -f "$decisions_dir/index.md" ]; then
    mkdir -p "$decisions_dir" 2>/dev/null || true
    _adr_regen_index "$decisions_dir"
    created+=("decisions/index.md")
  fi

  if [ ! -f "$wiki_root/glossary.md" ]; then
    _wb_glossary_template >"$wiki_root/glossary.md.tmp.$$" && mv "$wiki_root/glossary.md.tmp.$$" "$wiki_root/glossary.md"
    created+=("glossary.md")
  fi

  echo "WIKI_BOOTSTRAP_STATUS=ok"
  local IFS=,
  echo "WIKI_BOOTSTRAP_CREATED=${created[*]:-}"
  return 0
}

# ── term-drift check (task 3.5) ──────────────────────────────────────────────

# wiki_term_drift_check [<wiki-root>]
# Scans glossary.md for `### Term` entries carrying an `Avoid:` line (see
# docs/glossary-schema.md) and reports every wiki flow file or ADR that uses
# an avoided synonym instead of the preferred term. One violation per
# (file, synonym) pair — not per line — so a term repeated many times in one
# file doesn't flood the output; the file is what wiki-maintenance fixes, not
# the individual line. glossary.md itself and any generated index.md are
# skipped — an Avoid: line legitimately names its own synonym, and a
# registry table isn't prose. Reusable: called by lib/wiki-verify.sh and by
# the adr-gate skill before drafting ADR prose (docs/glossary-schema.md
# "Glossary informs ADR drafting"). Emits TERM_DRIFT|<file>|<avoided>|<term>
# lines. Exit 0 clean (or no glossary / no WIKI_ROOT), 1 violations found.
wiki_term_drift_check() {
  local wiki_root="${1:-${WIKI_ROOT:-}}"
  [ -z "$wiki_root" ] && return 0
  local glossary="$wiki_root/glossary.md"
  [ -f "$glossary" ] || return 0

  local files=()
  while IFS= read -r f; do
    files+=("$f")
  done < <(find "$wiki_root" -type f -name '*.md' ! -name 'glossary.md' ! -name 'index.md' 2>/dev/null)

  local term="" avoided_csv="" rc=0
  while IFS= read -r line; do
    case "$line" in
    "### "*)
      term="${line#"### "}"
      ;;
    "Avoid:"*)
      avoided_csv="${line#Avoid:}"
      [ -z "${avoided_csv//[[:space:]]/}" ] && continue
      [ ${#files[@]} -eq 0 ] && continue
      local syn
      while IFS= read -r syn; do
        syn=$(echo "$syn" | sed -E 's/^[[:space:]]+|[[:space:]]+$//g')
        [ -z "$syn" ] && continue
        local file
        for file in "${files[@]}"; do
          if grep -niqw -F -- "$syn" "$file" 2>/dev/null; then
            printf 'TERM_DRIFT|%s|%s|%s\n' "$file" "$syn" "$term"
            rc=1
          fi
        done
      done < <(echo "$avoided_csv" | tr ',' '\n')
      ;;
    esac
  done <"$glossary"

  return "$rc"
}

# ── CLI dispatch ─────────────────────────────────────────────────────────────

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
  wb_cmd="bootstrap"
  case "${1:-}" in
  bootstrap | term-drift)
    wb_cmd="$1"
    shift
    ;;
  esac

  wiki_root_arg=""
  while [ $# -gt 0 ]; do
    case "$1" in
    --wiki-root)
      wiki_root_arg="${2:-}"
      shift 2
      ;;
    -h | --help) _wb_die_usage ;;
    *)
      echo "wiki-bootstrap.sh: unknown flag '$1'" >&2
      _wb_die_usage
      ;;
    esac
  done

  case "$wb_cmd" in
  bootstrap)
    wiki_bootstrap "$wiki_root_arg"
    exit 0
    ;;
  term-drift)
    wiki_term_drift_check "$wiki_root_arg"
    exit $?
    ;;
  esac
fi
